language: go

go:
  - 1.9
  - master

before_install:
  - go get -t -v ./...
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet ./...
  - megacheck ./...
  - golint -set_exit_status $(go list ./...)
  - go test -v -race ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)